### ISSUE TITLE
图片无法写入服务器

### ISSUE THREAD

**Issue by MrQuJL** [MrQuJL/product-recommendation-system#4]
private static final String IMG_SERVER_PATH = "/product/category1";
File fileTemp = new File(IMG_SERVER_PATH);
if(!fileTemp.exists()){
	fileTemp.mkdirs();
}
			
File file = new File(IMG_SERVER_PATH + "/" + tempFileName);
System.out.println(IMG_SERVER_PATH + "/" + tempFileName);
uploadFile.transferTo(file);

**Comment by MrQuJL** [comment]
原因：必须使用绝对路径写入。
新问题：通过绝对路径写入，但是没有办法从服务器端根据绝对路径访问本机资源。
解决：新起一个项目，专门用来放图片，读取图片的时候，通过这个新项目的 url 来访问。

**Comment by Alone95** [comment]
你好，方便把你的最新数据库脚本上传一下吗？谢谢

**Comment by MrQuJL** [comment]
@Alone95  嗯嗯，好的，已上传，在 shopping-db 文件夹下，与用户相似度有关的两个表是 shopping_active, shopping_similarity。
